// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkWell.Infrastructure.Data;

#nullable disable

namespace WorkWell.Infrastructure.Migrations
{
    [DbContext(typeof(WorkWellDbContext))]
    partial class WorkWellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkWell.Domain.Entities.AlertaBurnout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ALERTA");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_LEITURA");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<bool>("Lido")
                        .HasColumnType("bit")
                        .HasColumnName("LIDO");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("int")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<string>("Recomendacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RECOMENDACOES");

                    b.Property<decimal>("ScoreRisco")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("SCORE_RISCO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("Lido");

                    b.HasIndex("NivelRisco");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ALERTAS_BURNOUT");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.CheckinDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_CHECKIN");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HorasSono")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("HORAS_SONO");

                    b.Property<decimal>("HorasTrabalhadas")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("HORAS_TRABALHADAS");

                    b.Property<int>("NivelStress")
                        .HasColumnType("int")
                        .HasColumnName("NIVEL_STRESS");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("OBSERVACOES");

                    b.Property<decimal?>("ScoreBemEstar")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("SCORE_BEMESTAR");

                    b.Property<string>("Sentimento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SENTIMENTO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DataCheckin");

                    b.ToTable("CHECKINS_DIARIOS");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("DEPARTAMENTOS");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CNPJ");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("Setor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SETOR");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("EMPRESAS");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.MetricaSaude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_REGISTRO");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("int")
                        .HasColumnName("FREQUENCIA_CARDIACA");

                    b.Property<decimal?>("LitrosAgua")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("LITROS_AGUA");

                    b.Property<int?>("MinutosAtividadeFisica")
                        .HasColumnType("int")
                        .HasColumnName("MINUTOS_ATIVIDADE_FISICA");

                    b.Property<int?>("PassosDiarios")
                        .HasColumnType("int")
                        .HasColumnName("PASSOS_DIARIOS");

                    b.Property<decimal?>("PesoKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("PESO_KG");

                    b.Property<int?>("QualidadeSono")
                        .HasColumnType("int")
                        .HasColumnName("QUALIDADE_SONO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DataRegistro");

                    b.ToTable("METRICAS_SAUDE");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CARGO");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ULTIMO_ACESSO");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("DEPARTAMENTO_ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("ROLE");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SENHA_HASH");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AlertaBurnout", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.CheckinDiario", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Checkins")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Departamentos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.MetricaSaude", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MetricasSaude")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorkWell.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Checkins");

                    b.Navigation("MetricasSaude");
                });
#pragma warning restore 612, 618
        }
    }
}
